CREATE TABLE IF NOT EXISTS `directoryItems` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `cdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `section` varchar(64) DEFAULT 'general',
  `parentId` int(10) unsigned DEFAULT NULL,
  `isCategory` tinyint(1) NOT NULL DEFAULT '0',
  `date` date DEFAULT NULL,
  `datetime` datetime DEFAULT NULL,
  `note1` varchar(64) DEFAULT NULL,
  `note2` varchar(64) DEFAULT NULL,
  `select1` varchar(16) DEFAULT NULL,
  `select2` varchar(16) DEFAULT NULL,
  `checkbox1` tinyint(1) DEFAULT NULL,
  `checkbox2` tinyint(1) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `token` varchar(3) NOT NULL,
  `alias` varchar(128) NOT NULL,
  `address` varchar(128) DEFAULT NULL,
  `phone` varchar(64) DEFAULT NULL,
  `email` varchar(64) DEFAULT NULL,
  `url` varchar(128) DEFAULT NULL,
  `price` decimal(15,2) DEFAULT NULL,
  `text1` text,
  `text2` text,
  `position` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cdate_idx` (`cdate`),
  KEY `name` (`name`),
  KEY `alias_idx` (`alias`),
  KEY `parent_idx` (`parentId`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `directoryImages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `cdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `hotspots` tinyint(1) NOT NULL DEFAULT '0',
  `section` varchar(64) DEFAULT 'general',
  `itemId` int(10) unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `alias` varchar(6) NOT NULL,
  `ext` varchar(8) NOT NULL,
  `resolution` varchar(9) NOT NULL,
  `select1` varchar(16) DEFAULT NULL,
  `select2` varchar(16) DEFAULT NULL,
  `checkbox1` tinyint(3) DEFAULT NULL,
  `checkbox2` tinyint(3) DEFAULT NULL,
  `text1` text,
  `text2` text,
  `position` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cdate_idx` (`cdate`),
  KEY `name_idx` (`name`),
  KEY `alias_idx` (`alias`),
  KEY `parent_idx` (`itemId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE `directoryHotspots` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
	`token` VARCHAR(6) NOT NULL ,
	`section` VARCHAR(64) DEFAULT 'general' ,
	`imageId` INT UNSIGNED NOT NULL ,
	`name` VARCHAR(128) NOT NULL ,
	`text1` TEXT NULL ,
	`points` TEXT NULL ,
	`resolution` VARCHAR(9) NOT NULL ,
	`position` INT UNSIGNED NULL ,
	PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `directoryAudios` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `cdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `section` varchar(64) DEFAULT 'general',
  `itemId` int(10) unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `alias` varchar(6) NOT NULL,
  `filename` varchar(256) NOT NULL,
  `ext` varchar(5) NOT NULL,
  `filesize` int(10) unsigned NOT NULL,
  `select1` varchar(16) DEFAULT NULL,
  `select2` varchar(16) DEFAULT NULL,
  `checkbox1` tinyint(3) DEFAULT NULL,
  `checkbox2` tinyint(3) DEFAULT NULL,
  `text1` text NOT NULL,
  `text2` text NOT NULL,
  `position` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cdate_idx` (`cdate`),
  KEY `name_idx` (`name`),
  KEY `alias_idx` (`alias`),
  KEY `parent_idx` (`itemId`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `directoryAttachments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `cdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `section` varchar(64) DEFAULT 'general',
  `itemId` int(10) unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `alias` varchar(6) NOT NULL,
  `filename` varchar(256) NOT NULL,
  `ext` varchar(8) NOT NULL,
  `filesize` int(10) unsigned NOT NULL,
  `select1` varchar(16) DEFAULT NULL,
  `select2` varchar(16) DEFAULT NULL,
  `checkbox1` tinyint(3) DEFAULT NULL,
  `checkbox2` tinyint(3) DEFAULT NULL,
  `text1` text NOT NULL,
  `text2` text NOT NULL,
  `position` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cdate_idx` (`cdate`),
  KEY `name_idx` (`name`),
  KEY `alias_idx` (`alias`),
  KEY `parent_idx` (`itemId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `directoryVideos` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `cdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `section` varchar(64) DEFAULT 'general',
  `itemId` int(10) unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `alias` varchar(128) NOT NULL,
  `type` int(2) DEFAULT NULL,
  `videoId` varchar(64) NOT NULL,
  `imgCustom` tinyint(1) DEFAULT NULL,
  `ext` varchar(8) NOT NULL,
  `filesize` int(10) unsigned NOT NULL,
  `select1` varchar(16) DEFAULT NULL,
  `select2` varchar(16) DEFAULT NULL,
  `checkbox1` tinyint(3) DEFAULT NULL,
  `checkbox2` tinyint(3) DEFAULT NULL,
  `text1` text,
  `text2` text,
  `position` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `alias_idx` (`alias`),
  KEY `cdate_idx` (`cdate`),
  KEY `parent_idx` (`itemId`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

ALTER TABLE `directoryItems` ADD INDEX `isCategory_idx` ( `isCategory` );
ALTER TABLE `directoryItems` ADD INDEX `section_idx` ( `section` );

