<?php
// messages
define('MESSAGE_INFO', 1);
define('MESSAGE_WARNING', 2);
define('MESSAGE_ERROR', 3);

// Confirmations
define('CONFIRMATION_EMAIL', 1);
define('CONFIRMATION_PASSWORD', 2);

// Date time
define('CURRENT_TIMESTAMP', time());
define('CURRENT_DATETIME', date('Y-m-d H:i:s', CURRENT_TIMESTAMP));
define('CURRENT_DATE', date('Y-m-d', CURRENT_TIMESTAMP));

define('VIDEO_TYPE_YOUTUBE', 1);
define('VIDEO_TYPE_VIMEO', 2);

define('FILE_PHOTOS', 1);
define('FILE_AUDIO', 2);
define('FILE_VIDEO', 3);

define('PAGE_TYPE_STATIC', 1);
define('PAGE_TYPE_GALLERY', 2);
define('PAGE_TYPE_BANNERS', 3);

define('PAGE_CATEGORY_HOME', 1);
define('PAGE_CATEGORY_POLICY', 2);
define('PAGE_CATEGORY_ABOUTUS', 5);
define('PAGE_CATEGORY_OURTEAM', 13);
define('PAGE_CATEGORY_ADVERTISE_WITH_US', 7);
define('PAGE_CATEGORY_SUPPORT', 12);
// -
define('POPUP_CATEGORY_CREATE_COMPANY', 8);
define('POPUP_CATEGORY_CREATE_GROUP', 9);
define('POPUP_CATEGORY_CREATE_SCHOOL', 10);
define('POPUP_CATEGORY_REGISTRATION_PEOPLE', 11);

define('USER_TYPE_WEBROOT', 'root');
define('USER_TYPE_WEBADMIN', 'admin');
define('USER_TYPE_USER', 1);
define('USER_TYPE_ADMIN', 2);

define('USER_PROFILE_VISIBLE', 0);
define('USER_PROFILE_INVISIBLE', 1);

define('USER_LEVEL_ACCESS_SHOW_CONNECTIONS', 1);
define('USER_LEVEL_ACCESS_SHOW_CONTACTINFO', 2);

define('ADDCONNECTION_SEND', 0);
define('ADDCONNECTION_APPROVED', 1);
define('ADDCONNECTION_DENY', 2);
define('ADDCONNECTION_VIRTUALAPPROVE', 3);

define('FILE_PAGES', 1);
define('FILE_UPDATES', 2);
define('FILE_USER_AVA', 3);
define('FILE_COMPANY_AVA', 4);
define('FILE_COMPANY_COVER', 5);
define('FILE_GROUP_EMBLEM', 6);
define('FILE_GROUP_COVER', 7);
define('FILE_JOB_APPLY', 8);
define('FILE_SCHOOL_AVA', 9);
define('FILE_SCHOOL_COVER', 10);
define('FILE_BANNER', 11);

define('MESSAGE_INBOX', 0);
define('MESSAGE_ARCHIVE', 1);
define('MESSAGE_TRASH', 2);
define('MESSAGE_DELETE', 3);

define('NOTIFICATION_TYPE_LIKEPOST', 1);
define('NOTIFICATION_TYPE_COMMENTPOST', 2);
define('NOTIFICATION_TYPE_VIEWPROFILE', 3);
define('NOTIFICATION_TYPE_NEWCONNECTION', 4);
define('NOTIFICATION_TYPE_ENDORSESKILL', 5);
define('NOTIFICATION_TYPE_APPLICANTAPPROVE', 6);
define('NOTIFICATION_TYPE_APPLICANTDENY', 7);
define('NOTIFICATION_TYPE_APPLICANTNEW', 8);

define('POST_TYPE_TEXT', 1);
define('POST_TYPE_IMAGE', 2);
define('POST_TYPE_WEB', 3);
define('POST_TYPE_PDF', 4);
define('POST_TYPE_DOC', 5);

define('TIMELINE_TYPE_POST', 1);
define('TIMELINE_TYPE_SHAREPOST', 2);
define('TIMELINE_TYPE_STARTDISCUSSIONS', 3);
define('TIMELINE_TYPE_JOIN', 4);
define('TIMELINE_TYPE_LIKE', 5);
define('TIMELINE_TYPE_NEWCONNECTION', 6);
define('TIMELINE_TYPE_FOLLOW', 7);
define('TIMELINE_TYPE_UPDATEPHOTO', 8);
define('TIMELINE_TYPE_NEWJOB', 9);
define('TIMELINE_TYPE_COMMENTS', 10);

define('TIMELINE_TYPE_LIKEDUSCUSSION', 11);
define('TIMELINE_TYPE_COMMENTSDUSCUSSION', 12);

define('UPDATE_CATEGORY_PEOPLE', 1);
define('UPDATE_CATEGORY_COMPANY', 2);
define('UPDATE_CATEGORY_GROUP', 3);
define('UPDATE_CATEGORY_SCHOOL', 4);
define('UPDATE_CATEGORY_GROUP_CHECK_CONTENT', 10);

define('GROUP_MEMBER_TYPE_USER', 1);
define('GROUP_MEMBER_TYPE_ADMIN', 2);

define('GROUP_ACCES_TYPE_FREE', 1);
define('GROUP_ACCES_TYPE_APPROVAL', 2);

define('GROUP_DISSCUSSION_TYPE_FREE', 1);
define('GROUP_DISSCUSSION_TYPE_APPROVAL', 2);

define('JOBAPPLY_ANSWER_NULL', 0);
define('JOBAPPLY_ANSWER_APPROVE', 1);
define('JOBAPPLY_ANSWER_DENY', 2);

define('ACCOUNT_TYPE_BASIC', 0);
define('ACCOUNT_TYPE_GOLD', 1);

define('SCHOOL_TYPEMEMBER_SENT_REQUEST', 0);
define('SCHOOL_TYPEMEMBER_STAFF', 1);

define('NETWORK_TYPE_ALL', 1);
define('NETWORK_TYPE_ME', 2);
define('NETWORK_TYPE_MYCONNECTIONS', 3);
define('NETWORK_TYPE_MYNETWORK', 4);

define('CATEGORY_PLAN_JOB', 1);
define('CATEGORY_PLAN_PROFILE', 2);

define('FIELD_INPUT', 1);
define('FIELD_TEXTAREA', 2);
define('FIELD_SELECT', 3);
define('FIELD_CHECKBOX', 4);
define('FIELD_CHECKBOXES', 5);
define('FIELD_FILE_ONE', 6);