CREATE TABLE IF NOT EXISTS `cartOrders` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `amount` decimal(15,2) DEFAULT NULL,
  `delivery` text,
  `deliveryCost` float DEFAULT NULL,
  `discount` varchar(15) DEFAULT NULL,
  `processed` tinyint(3) DEFAULT NULL,
  `isPaid` tinyint(4) NOT NULL DEFAULT '0',
  `dateTimeAdded` datetime DEFAULT NULL,
  `dateTimePaid` datetime DEFAULT NULL,
  `token` varchar(6) NOT NULL,
  `sessionId` varchar(64) NOT NULL,
  `transactionId` varchar(64) NOT NULL,
  `customer` varchar(128) DEFAULT NULL,
  `email` varchar(64) DEFAULT NULL,
  `state` varchar(2) DEFAULT NULL,
  `zip` varchar(5) DEFAULT NULL,
  `city` varchar(128) DEFAULT NULL,
  `address` varchar(128) DEFAULT NULL,
  `phone` varchar(64) DEFAULT NULL,
  `comment` text,
  `paypalLink` text,
  `paypalRecurringStatus` varchar(64) DEFAULT NULL,
  `paypalRecurringProfileId` varchar(64) DEFAULT NULL,
  `paypalMethod` varchar(64) DEFAULT NULL,
  `paypalToken` varchar(64) DEFAULT NULL,
  `paypalEmail` varchar(64) DEFAULT NULL,
  `paypalAck` varchar(64) DEFAULT NULL,
  `paypalMessage` text,
  `paypalInfo` text,
  `paypalCorrelationId` varchar(64) DEFAULT NULL,
  `paypalTimestamp` varchar(64) DEFAULT NULL,
  `position` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `cartItems` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `orderId` int(10) unsigned NOT NULL,
  `itemId` int(10) unsigned NOT NULL,
  `itemName` varchar(64) NOT NULL,
  `note` varchar(64) DEFAULT NULL,
  `source` varchar(64) DEFAULT 'directory',
  `section` varchar(64) DEFAULT NULL,
  `quantity` int(11) NOT NULL,
  `price` decimal(15,2) DEFAULT NULL,
  `details` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;