/*
SQLyog Ultimate v9.50 
MySQL - 5.5.25 : Database - mekoo
*********************************************************************
*/


/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`mekoo` /*!40100 DEFAULT CHARACTER SET utf8 */;



INSERT INTO `settings` (`name`, `key`, `value`, `type`, `rules`, `options`, `root`, `position`) VALUES
('Website title', 'title', 'Website title', 'text', '{"required":true, "maxLength":250}', NULL, NULL, 1),
('Contact email', 'email', 'test@test.net', 'text', '{"required":true, "email":true}', NULL, NULL, 2);

INSERT INTO `users` (`id`, `name`, `token`, `password`, `firstName`, `lastName`, `email`, `role`) VALUES
(1, 'admin', '', 'adf872hf7e4c0d4f62d05e5b4f8d42acabdef1ae06c4b949', 'Admin', 'Admin', 'admin@test.net', 'root'),
(2, 'user', '', 'adf872hf7e4c0d4f62d05e5b4f8d42acabdef1ae06c4b949', 'User', 'Sample', 'test@test.net', 'admin'),
(3, 'ukietech', '', '608d6a0bcfcc825ccac7ae94d9e8a8d1d31561d1998bb86d', 'Ukietech', 'user', 'mail@ukietech.com', 'root');

/*Data for the table `pages_category` */
insert  into `page_category`(`id`,`name`,`subCategory`,`isBlocked`) values (1,'Home page',NULL,0),(2,'Privacy policy',NULL,0),(5,'About us',NULL,0),(6,'Background gallery on start page',NULL,0),(7,'Advertise with us',NULL,0),(8,'Terms of use \"create company\"',NULL,0),(9,'Terms of use \"create group\"',NULL,0),(10,'Terms of use \"create school\"',NULL,0),(11,'Terms of use \"registration people\"',NULL,0);

/*Data for the table `pages` */
insert  into `pages`(`id`,`createDate`,`updateDate`,`category`,`alias`,`title`,`text`,`config`,`isPublic`,`isRemoved`) values (20,'2014-05-23 11:26:21','2014-05-26 05:15:35','static','home-page','Home page','<p style=\"text-align:justify\">Quisque ullamcorper orci ligula. Suspendisse posuere, justo vel sodales aliquam, mauris enim ultricies nisi, vitae imperdiet purus mi ac lacus. Ut elementum enim ut elit malesuada sagittis. Curabitur tempor, metus at hendrerit sollicitudin, metus quam pellentesque nisl, quis consequat arcu tellus sit amet erat. Sed vulputate congue justo tempor rutrum. Vivamus cursus, mauris id fermentum tempus, odio nibh venenatis est, sit amet faucibus justo nisl gravida libero. Mauris sit amet nunc feugiat, blandit risus at, aliquam mi. Praesent accumsan mattis odio vitae congue. Sed dapibus imperdiet aliquam. Morbi luctus ac ipsum congue aliquet. Donec non lorem metus. In dolor justo, ultrices quis est at, pretium pellentesque leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam varius leo in arcu adipiscing, a lobortis eros aliquet. Donec tempus viverra lectus quis dictum.</p>\r\n\r\n<p style=\"text-align:justify\">Aliquam vitae dolor felis. Integer faucibus nec dui non mattis. Aliquam iaculis fermentum luctus. Ut nec aliquet augue. Vestibulum consequat turpis vel est sollicitudin, et egestas velit mattis. Aliquam ac dignissim libero, a mattis ligula. Integer quis diam id leo sagittis euismod. Fusce commodo quam mollis lectus venenatis ultrices. Nulla eget nulla justo. Cras non malesuada arcu, eget lacinia ante. Nulla facilisi. Nullam ut libero eu ipsum euismod auctor sit amet in felis. Aliquam mollis bibendum arcu at tincidunt. Pellentesque vitae metus scelerisque, pellentesque ipsum eget, dictum orci. Vivamus porta purus velit, in adipiscing velit vehicula eu.</p>\r\n\r\n<p style=\"text-align:justify\">Cras tellus nibh, lobortis vel nisi vitae, lobortis lacinia lorem. Etiam tempus, ipsum ut pharetra bibendum, lacus dolor convallis dolor, pellentesque fermentum nisl leo at dui. Quisque tempor, magna at tincidunt porta, neque erat sagittis odio, et pellentesque mi ante sed augue. In pharetra libero eget purus interdum molestie. Vivamus varius auctor ipsum, vehicula fermentum quam aliquet vel. Fusce bibendum dui ut neque convallis, sit amet commodo augue faucibus. Nunc pellentesque, ipsum sed ornare sollicitudin, dui massa aliquam diam, eu iaculis elit massa vitae quam. Sed pretium accumsan justo, non porttitor metus vehicula non. Praesent ullamcorper leo ut ultrices accumsan. Curabitur eleifend tellus malesuada tincidunt cursus. Morbi a metus lacus.</p>\r\n\r\n<p>&nbsp;</p>\r\n',NULL,0,0),(21,'2014-05-23 11:26:53','0000-00-00 00:00:00','static','privacy-policy','Privacy policy','<p style=\"text-align:justify\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus semper tortor ut ligula varius mattis eu nec nisi. Praesent vehicula metus eget risus convallis sodales. Proin interdum tincidunt lacus. Praesent varius volutpat convallis. Cras pellentesque, erat eu elementum viverra, diam risus pharetra nisi, quis dignissim odio sem ut mauris. Quisque nec diam interdum, mattis est sit amet, volutpat eros. Praesent vulputate, libero sit amet mollis molestie, quam lorem bibendum nunc, quis lacinia ipsum velit id odio. Vivamus enim lectus, varius id malesuada non, luctus et metus. Cras quis venenatis libero. Mauris nec mi hendrerit, pharetra diam eu, feugiat orci. Nunc vel ipsum augue.</p>\r\n\r\n<p style=\"text-align:justify\">Nunc pulvinar laoreet lectus, in gravida tellus. Praesent at dictum ante. Nam lectus arcu, malesuada nec sollicitudin et, ornare vitae velit. Maecenas cursus sit amet urna eget iaculis. Ut sit amet porta metus, quis accumsan mauris. Sed facilisis felis at turpis pellentesque consequat. Quisque eleifend elementum aliquam. Donec accumsan dolor sed orci laoreet dignissim. Phasellus dapibus risus justo, tincidunt semper ante commodo sit amet. Quisque tincidunt dui sit amet tellus sollicitudin, in tempus eros sagittis. Sed euismod rutrum ipsum eu tristique.</p>\r\n\r\n<p style=\"text-align:justify\">Phasellus a bibendum ante. Maecenas condimentum rutrum fringilla. Morbi ut tortor sapien. Aliquam ornare metus non ultrices auctor. Sed posuere porta sagittis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In posuere dolor id tortor vestibulum sollicitudin. Donec id enim eu odio mattis imperdiet placerat at ipsum. Curabitur non pellentesque justo. Morbi suscipit lacinia nisi, quis tincidunt elit faucibus id. Sed tristique augue at quam consectetur, at eleifend nibh posuere. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sollicitudin dolor id venenatis malesuada. Nunc at nulla a sem mollis dignissim vitae sed tellus. Sed sit amet est vitae quam euismod mollis.</p>\r\n\r\n<p style=\"text-align:justify\">Ut mollis tortor ut tortor dapibus malesuada. Aliquam consequat tortor leo, non vestibulum quam bibendum ut. Sed vel dignissim lorem. Integer pretium nisl eros, ac hendrerit nisl rutrum nec. Nullam quis mollis turpis. Cras in tortor porta, congue erat at, malesuada neque. Nam eu tortor lectus.</p>\r\n\r\n<p style=\"text-align:justify\">Quisque ullamcorper orci ligula. Suspendisse posuere, justo vel sodales aliquam, mauris enim ultricies nisi, vitae imperdiet purus mi ac lacus. Ut elementum enim ut elit malesuada sagittis. Curabitur tempor, metus at hendrerit sollicitudin, metus quam pellentesque nisl, quis consequat arcu tellus sit amet erat. Sed vulputate congue justo tempor rutrum. Vivamus cursus, mauris id fermentum tempus, odio nibh venenatis est, sit amet faucibus justo nisl gravida libero. Mauris sit amet nunc feugiat, blandit risus at, aliquam mi. Praesent accumsan mattis odio vitae congue. Sed dapibus imperdiet aliquam. Morbi luctus ac ipsum congue aliquet. Donec non lorem metus. In dolor justo, ultrices quis est at, pretium pellentesque leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam varius leo in arcu adipiscing, a lobortis eros aliquet. Donec tempus viverra lectus quis dictum.</p>\r\n\r\n<p style=\"text-align:justify\">Aliquam vitae dolor felis. Integer faucibus nec dui non mattis. Aliquam iaculis fermentum luctus. Ut nec aliquet augue. Vestibulum consequat turpis vel est sollicitudin, et egestas velit mattis. Aliquam ac dignissim libero, a mattis ligula. Integer quis diam id leo sagittis euismod. Fusce commodo quam mollis lectus venenatis ultrices. Nulla eget nulla justo. Cras non malesuada arcu, eget lacinia ante. Nulla facilisi. Nullam ut libero eu ipsum euismod auctor sit amet in felis. Aliquam mollis bibendum arcu at tincidunt. Pellentesque vitae metus scelerisque, pellentesque ipsum eget, dictum orci. Vivamus porta purus velit, in adipiscing velit vehicula eu.</p>\r\n\r\n<p style=\"text-align:justify\">Cras tellus nibh, lobortis vel nisi vitae, lobortis lacinia lorem. Etiam tempus, ipsum ut pharetra bibendum, lacus dolor convallis dolor, pellentesque fermentum nisl leo at dui. Quisque tempor, magna at tincidunt porta, neque erat sagittis odio, et pellentesque mi ante sed augue. In pharetra libero eget purus interdum molestie. Vivamus varius auctor ipsum, vehicula fermentum quam aliquet vel. Fusce bibendum dui ut neque convallis, sit amet commodo augue faucibus. Nunc pellentesque, ipsum sed ornare sollicitudin, dui massa aliquam diam, eu iaculis elit massa vitae quam. Sed pretium accumsan justo, non porttitor metus vehicula non. Praesent ullamcorper leo ut ultrices accumsan. Curabitur eleifend tellus malesuada tincidunt cursus. Morbi a metus lacus.</p>\r\n\r\n<p style=\"text-align:justify\">Quisque interdum consequat dignissim. Nam iaculis aliquam erat quis dignissim. Integer pulvinar elementum mi, sit amet feugiat justo auctor nec. Suspendisse venenatis ac magna nec commodo. Donec consectetur tempor augue, vel lacinia est viverra sed. Nullam pharetra mauris eu diam suscipit ornare. Vestibulum vel diam ornare justo lacinia ullamcorper. Praesent non mi pharetra, consequat quam quis, facilisis libero. Sed fringilla magna eget facilisis condimentum. Sed nisi neque, rutrum eget sapien in, tempor volutpat nulla. Proin rhoncus a dolor a congue.</p>\r\n\r\n<p style=\"text-align:justify\">Quisque feugiat, nunc eu pellentesque fringilla, tortor lacus viverra diam, eu pretium libero ligula eget mi. Fusce elementum turpis et sodales mollis. Mauris pharetra nunc vel dui placerat lobortis. Morbi vestibulum sapien orci, condimentum placerat purus sodales eu. Proin felis orci, vestibulum nec aliquam faucibus, condimentum at orci. Aliquam sed mi non lacus convallis tincidunt eget sit amet eros. Maecenas bibendum fermentum leo, eget porta risus facilisis nec. Vestibulum consequat eros quis urna gravida luctus. Nullam sollicitudin erat lorem, ac sodales dui accumsan vel. Fusce sagittis laoreet condimentum. Nam non elementum eros. Nam ultrices nunc odio, ut malesuada odio hendrerit quis.</p>\r\n\r\n<p style=\"text-align:justify\">Quisque nec sapien orci. Maecenas dapibus, diam eu faucibus convallis, urna velit laoreet sapien, eget consectetur ipsum purus quis sem. Ut risus odio, porta vitae ultrices congue, vestibulum in velit. Donec nec gravida eros. Aliquam erat volutpat. Morbi nisi lorem, fringilla at volutpat id, tincidunt non velit. Curabitur feugiat nunc sed orci iaculis, eu ultrices massa tempor. Morbi risus tortor, accumsan eu massa ut, pellentesque aliquet enim. Quisque nec adipiscing arcu. Suspendisse vitae eleifend nisl. Proin id felis gravida, aliquam velit eget, pulvinar mi. Suspendisse leo elit, volutpat in mi sit amet, ultricies tempor nisl. Proin rutrum pharetra placerat. Sed magna enim, gravida eget magna sed, malesuada accumsan ligula. Ut condimentum tempor massa id feugiat.</p>\r\n\r\n<p style=\"text-align:justify\">Suspendisse ultricies blandit nibh et pulvinar. Aenean euismod a leo sit amet lobortis. Aenean eleifend rhoncus lobortis. Nulla facilisi. In fringilla justo nibh, hendrerit fringilla tellus elementum nec. Aenean pellentesque dapibus risus a hendrerit. Duis nec fringilla massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus commodo elementum interdum. Nunc faucibus, sapien id rutrum interdum, turpis sem sodales erat, sit amet mattis dui lectus a erat. Etiam iaculis orci quam, quis ultricies dolor euismod sed. Pellentesque sed pellentesque nisi, nec fringilla urna. Integer eget nunc nunc.</p>\r\n\r\n<p style=\"text-align:justify\">Curabitur eleifend, justo vel dapibus ullamcorper, risus lectus cursus ipsum, eu blandit arcu ipsum quis arcu. Duis pharetra nisi ut elit mattis, non consequat elit elementum. Donec eu felis ultrices, varius felis at, mollis sapien. Suspendisse potenti. Praesent congue nulla sem, vitae pulvinar mauris rutrum non. Curabitur elit ipsum, dictum a sem at, gravida rhoncus tellus. Etiam lectus ligula, porttitor nec sollicitudin et, tincidunt nec nulla.</p>\r\n\r\n<p style=\"text-align:justify\">Sed scelerisque a nisi sit amet fringilla. Ut eget elementum arcu, vel blandit ipsum. Donec dictum varius nibh vitae lobortis. Phasellus bibendum, turpis et condimentum pretium, orci massa sollicitudin quam, vel bibendum magna lacus eu urna. Duis iaculis tempus est, et placerat justo convallis ut. Nam suscipit lectus nec lorem blandit viverra. Nunc id venenatis neque. Nulla accumsan neque vel nulla varius, a ultricies ipsum gravida. Nunc quis lacinia elit, id iaculis lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum cursus faucibus rutrum. Proin dignissim dictum ullamcorper. Curabitur congue sollicitudin risus nec laoreet. Proin velit turpis, pretium a eros nec, viverra interdum nibh. Fusce odio lectus, placerat sit amet erat non, fermentum volutpat mauris. Pellentesque feugiat ultricies metus et eleifend.</p>\r\n\r\n<p style=\"text-align:justify\">Aenean et faucibus lacus. Duis gravida tincidunt enim ac mollis. Etiam quis ipsum justo. Nam enim neque, dignissim non mauris non, convallis ultricies lorem. Nam molestie metus risus, et suscipit eros sagittis sed. Pellentesque scelerisque augue purus, a convallis risus mattis a. Integer a neque vitae est imperdiet euismod.</p>\r\n\r\n<p style=\"text-align:justify\">Proin tincidunt tincidunt vestibulum. Ut tristique tincidunt nulla et luctus. Vestibulum id vulputate tellus, at dictum tellus. Pellentesque massa nibh, blandit a ipsum scelerisque, malesuada vehicula lorem. Nullam vel erat id est sollicitudin elementum. Praesent diam risus, auctor eget lectus sed, ultricies convallis ipsum. Donec justo arcu, fermentum eu vestibulum eget, commodo sed risus. Morbi magna arcu, dapibus eget sapien quis, lacinia hendrerit dui. Curabitur consequat faucibus felis a imperdiet.</p>\r\n\r\n<p style=\"text-align:justify\">Nam mi lorem, pretium eu nisl sit amet, scelerisque ullamcorper augue. Ut feugiat ante eu felis tempor faucibus. Integer sit amet leo urna. Nulla commodo dolor diam, vitae luctus tellus tincidunt ullamcorper. Phasellus dapibus, quam a interdum mollis, nulla justo facilisis quam, quis tempor sapien metus id felis. Suspendisse gravida commodo mi eget porta. Phasellus sed risus et arcu sollicitudin interdum nec et eros. Nulla fermentum a ante nec mattis. Duis id luctus mi. Phasellus mauris neque, tincidunt nec neque non, commodo dapibus dolor. Etiam vehicula egestas magna in lacinia. Curabitur in lorem nibh. Curabitur viverra tincidunt nisi vitae adipiscing. Mauris placerat erat adipiscing condimentum ultrices. Fusce tincidunt nunc in nibh mollis luctus. Suspendisse sed dui neque.</p>\r\n\r\n<p style=\"text-align:justify\">Nam eleifend venenatis tincidunt. Sed et leo sed quam commodo rhoncus. In hac habitasse platea dictumst. Praesent a ipsum tempus, pulvinar turpis sed, porta arcu. Aenean imperdiet sed nisi quis euismod. Nulla sit amet orci fringilla, mattis ipsum ut, placerat quam. Integer sit amet nulla ipsum. Nam dictum sapien sit amet erat facilisis semper. Vivamus aliquam placerat facilisis. Donec laoreet tempor facilisis. Phasellus vel turpis et enim gravida rhoncus sed sed est. Donec vulputate urna metus, a ultricies nisi egestas non. Cras ac nisl sit amet orci mattis mollis.</p>\r\n\r\n<p style=\"text-align:justify\">Morbi blandit turpis lorem, non semper dolor molestie nec. Nunc eget lacinia purus. Suspendisse rutrum nisi id diam sodales dignissim. In eleifend venenatis lectus, at sollicitudin nibh hendrerit quis. Fusce ac luctus arcu. Suspendisse potenti. Nunc vel ipsum facilisis, pellentesque turpis a, varius dolor. Morbi vulputate imperdiet est, at malesuada mauris viverra et.</p>\r\n\r\n<p style=\"text-align:justify\">Proin mattis nisi et pellentesque vestibulum. Maecenas nulla purus, porttitor nec ornare vel, rutrum in velit. Cras commodo quam et massa placerat egestas non sit amet ligula. In vitae mauris rhoncus, faucibus tortor eget, porta nulla. Vivamus a tortor hendrerit, semper tortor at, commodo erat. In mi ligula, venenatis sit amet viverra id, gravida sed ante. Nam ut pharetra augue, sit amet convallis lacus.</p>\r\n\r\n<p style=\"text-align:justify\">In non risus sed nibh ullamcorper aliquet vitae a sapien. Phasellus in mi viverra, sollicitudin neque auctor, interdum elit. Nunc id augue at dolor aliquet faucibus. Sed rutrum, arcu id ornare porttitor, est ipsum rhoncus massa, vitae sagittis urna est nec est. In varius sapien at augue mattis blandit. Duis rhoncus nunc sapien, ornare imperdiet massa faucibus a. Donec nulla nulla, dignissim at tincidunt et, suscipit id erat. Sed mattis augue sed mi vestibulum varius. Proin eu aliquet lorem, id dictum arcu. Vivamus scelerisque magna massa, vel viverra metus varius at.</p>\r\n\r\n<p style=\"text-align:justify\">Duis iaculis velit ac justo cursus eleifend at sagittis ipsum. Maecenas rhoncus ornare odio, eu auctor ante dapibus eget. Suspendisse pharetra dapibus nisi, et scelerisque purus. Aenean nec dolor eget neque lobortis elementum in tempor lacus. Nam dapibus eros vel tortor aliquam consequat. Integer sit amet nunc arcu. Nunc vel lectus metus. Nulla facilisi. Curabitur lobortis arcu euismod lacus imperdiet, adipiscing pharetra risus scelerisque. Integer iaculis erat a felis sollicitudin, sed viverra diam sollicitudin. Phasellus ullamcorper bibendum velit vel dignissim. Duis at condimentum orci. Vestibulum consequat, arcu sodales molestie pellentesque, lectus mauris aliquam urna, nec porttitor turpis odio non dui.</p>\r\n\r\n<p style=\"text-align:justify\">Praesent ut vulputate purus. Donec mattis sodales fermentum. Maecenas vehicula diam ac fringilla rutrum. Sed vitae risus sit amet lectus porttitor interdum nec accumsan tellus. Morbi lacinia accumsan odio, vel commodo nibh sodales non. Fusce blandit tellus mauris, eu pulvinar purus commodo sit amet. Aenean at sem non turpis semper interdum. Praesent ut metus non nisl scelerisque lobortis a in risus. Quisque in erat euismod, convallis justo in, bibendum purus. Proin dolor nibh, ornare eu est sit amet, posuere semper tellus. In justo dolor, eleifend id est sit amet, mattis dictum magna. Suspendisse urna elit, pulvinar ut ultricies quis, lacinia in quam. Etiam sodales lacus lorem, non interdum mauris vehicula non. Nam gravida ipsum eget justo venenatis, sed pulvinar erat sollicitudin. Mauris eu feugiat turpis.</p>\r\n\r\n<p style=\"text-align:justify\">Morbi sit amet iaculis elit. Cras nunc mauris, vulputate non mollis ut, lacinia id neque. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus sed scelerisque augue, eget gravida est. In pulvinar egestas purus quis tincidunt. Ut sed tempor enim. Curabitur id sollicitudin lectus, eu interdum enim. Quisque vel eros iaculis, vehicula odio sed, venenatis risus. Etiam non viverra diam. Vivamus imperdiet, erat nec volutpat vestibulum, neque augue ultrices justo, at hendrerit nisl nisl sed lacus. Phasellus purus metus, egestas vitae dictum nec, condimentum eu massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer condimentum accumsan odio, gravida euismod nibh blandit vitae.</p>\r\n\r\n<p style=\"text-align:justify\">Pellentesque quis nulla dictum nisi faucibus mollis. Ut dignissim facilisis est. Morbi luctus orci eros, a ullamcorper ligula imperdiet in. Ut laoreet pretium tellus non euismod. Vivamus ac aliquam enim. Ut pharetra, nulla vitae imperdiet auctor, lectus orci placerat ipsum, vitae viverra nisl nulla non quam. Mauris auctor egestas massa ac varius. In nec auctor eros. Curabitur purus tellus, molestie at lacinia ut, volutpat eu diam. Phasellus vel est in metus pellentesque dapibus. Suspendisse sed justo sit amet sapien mollis accumsan.</p>\r\n\r\n<p style=\"text-align:justify\">Phasellus vel arcu mollis massa adipiscing tincidunt ut quis purus. Curabitur sed enim a mauris posuere eleifend eu at lectus. Aliquam in posuere risus, in molestie neque. Phasellus tempus nisi in ante convallis vulputate. Praesent sapien sem, convallis sit amet neque vel, mollis posuere augue. Mauris et posuere ligula. Ut congue in ipsum ut posuere. Praesent pharetra, lacus eget porttitor eleifend, libero neque imperdiet ipsum, id egestas libero odio sit amet leo. Donec cursus tortor pretium nisl ornare, nec placerat orci tempor.</p>\r\n\r\n<p style=\"text-align:justify\">Nullam ligula ipsum, mattis a porta ut, iaculis eget massa. Donec dapibus est in felis rutrum, in tempor risus pulvinar. Aliquam tincidunt gravida consequat. Duis ut turpis adipiscing, interdum sem quis, tempus neque. In egestas pellentesque metus, non mollis sem viverra ut. Vivamus non accumsan elit. Proin eget augue sit amet lorem pulvinar posuere interdum id nulla. Sed sit amet risus massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel lorem sodales, rhoncus nunc ac, accumsan justo. Nulla et turpis eu lectus consequat semper. Integer mollis et erat sit amet pulvinar. Maecenas sed laoreet diam. Duis molestie volutpat turpis, quis dignissim lacus luctus id.</p>\r\n\r\n<p style=\"text-align:justify\">Nunc a nisl sagittis, tempus metus vitae, feugiat ligula. Proin id odio magna. Quisque eget imperdiet est, at viverra felis. Pellentesque aliquet mauris eget ultricies sodales. Integer semper ante eu neque porta, sed euismod quam dapibus. Quisque ac interdum ante. Nam pulvinar eleifend massa, sed gravida odio porta id.</p>\r\n\r\n<p style=\"text-align:justify\">Maecenas sit amet sodales elit. Aliquam erat volutpat. Vestibulum venenatis, augue blandit ornare ultricies, ipsum tortor fermentum ligula, non cursus risus augue ut ipsum. Etiam vel neque adipiscing, interdum erat quis, commodo nibh. Aenean porttitor felis dictum lorem consequat eleifend. Nam quis tortor sem. Suspendisse ac malesuada magna, nec aliquam eros.</p>\r\n\r\n<p style=\"text-align:justify\">Suspendisse dui urna, aliquet eget tristique nec, pretium sit amet felis. Sed pellentesque lectus id enim vestibulum, sed vehicula sem ornare. Proin quis aliquet turpis. Etiam a cursus tellus. Donec venenatis egestas ante, ut posuere tellus auctor a. Integer eros leo, lobortis ut tempor eget, gravida et lorem. Proin quis quam ornare, pellentesque enim sagittis, ornare est.</p>\r\n\r\n<p style=\"text-align:justify\">Pellentesque bibendum ipsum a libero lobortis laoreet. Curabitur purus ligula, pellentesque a est eu, vehicula placerat tortor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam ullamcorper dolor non convallis feugiat. Nunc mollis mauris a felis sollicitudin, ut volutpat nisi feugiat. Sed volutpat justo posuere lectus iaculis, non laoreet enim pellentesque. Aenean et viverra ipsum, non iaculis lorem. Donec sit amet sodales nunc. Praesent laoreet tortor eu tortor scelerisque dignissim.</p>\r\n\r\n<p style=\"text-align:justify\">Etiam semper posuere justo vel feugiat. Maecenas sed leo eu risus elementum tempor. Nam volutpat, nisi vitae ullamcorper imperdiet, elit lectus mollis elit, ac viverra nunc orci ac metus. Donec luctus odio sit amet neque lobortis, at porta lacus viverra. Mauris mattis justo nec massa varius, et adipiscing augue viverra. Morbi id cursus risus, eget bibendum lorem. Maecenas purus felis, consectetur vitae pellentesque nec, commodo in dui. Vestibulum non ipsum vel ante fermentum pharetra id ac est. Donec leo nulla, vehicula eget laoreet consequat, malesuada eleifend orci. Aliquam ut odio viverra, tincidunt orci vitae, volutpat enim. Quisque id massa eget quam dignissim cursus non ut odio.</p>\r\n\r\n<p style=\"text-align:justify\">Curabitur sed faucibus massa. Pellentesque placerat pharetra elementum. Quisque facilisis metus eu commodo consequat. Suspendisse eros lectus, vehicula vel nunc vitae, lacinia condimentum massa. Fusce facilisis sollicitudin bibendum. Quisque sollicitudin ante et justo mattis feugiat fringilla vel ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc quis pretium lacus, id mattis mi. Curabitur elit libero, congue in rhoncus ut, gravida quis augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque accumsan mauris a placerat cursus. Fusce eget sapien nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed dictum enim eget ipsum dignissim gravida. Aliquam quis quam vulputate mauris posuere laoreet. Aliquam pellentesque consectetur nisi.</p>\r\n\r\n<p style=\"text-align:justify\">Nullam vitae consequat mauris, lacinia tincidunt enim. Curabitur convallis diam felis, pulvinar pellentesque tellus suscipit in. Pellentesque et turpis eu tellus interdum pharetra. Sed ante ipsum, auctor nec ornare ut, venenatis vel tortor. Pellentesque nec quam mollis, imperdiet est eu, pretium turpis. Donec laoreet facilisis dolor id pharetra. Sed tempus mauris molestie lectus fermentum, vulputate vestibulum enim mollis. Donec quis mauris nec enim sollicitudin lacinia et a velit. Morbi ultricies mauris at viverra iaculis. Ut a fringilla nisl, vitae aliquam erat. Etiam et cursus odio, scelerisque mollis lorem. Nullam sed condimentum elit, id varius ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eleifend pharetra tristique. Aenean at imperdiet erat.</p>\r\n\r\n<p style=\"text-align:justify\">Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris pharetra velit nulla. Suspendisse eu dui quis massa ornare sollicitudin in non est. Phasellus interdum, nunc id molestie ultricies, enim ligula adipiscing lacus, et vestibulum dolor mi sed metus. Nulla quis vehicula sapien. Integer iaculis orci eget enim luctus, et tempor lectus pharetra. Nulla scelerisque libero sit amet auctor tincidunt. Donec laoreet nulla nec elit condimentum aliquet eget vel nibh.</p>\r\n\r\n<p style=\"text-align:justify\">Aliquam erat volutpat. Duis augue nisl, hendrerit sit amet risus ac, posuere ornare elit. Ut convallis, diam sed pellentesque ultrices, nibh turpis rhoncus ipsum, et hendrerit turpis metus ut risus. Nulla tristique justo non augue congue ullamcorper. Sed libero nibh, porttitor in justo non, posuere placerat lorem. Duis eu risus ultricies, placerat elit vel, ultrices libero. Mauris aliquam pharetra eleifend. Maecenas euismod a lorem vel interdum. Maecenas nec auctor orci. Aenean a libero in ipsum consequat pretium. Donec viverra velit eget consequat congue. Sed scelerisque lectus id nisl lobortis, bibendum varius massa dictum. Donec vel magna vel nisl feugiat volutpat vitae in leo. Pellentesque auctor libero vitae nulla tincidunt, tincidunt fermentum enim fermentum.</p>\r\n\r\n<p style=\"text-align:justify\">Mauris mattis, quam at volutpat auctor, massa magna commodo orci, in varius magna neque vel lacus. Aenean bibendum arcu eget aliquet feugiat. Aenean ac ipsum ac massa ultrices ultricies. Nam volutpat eleifend varius. Donec commodo dui in risus condimentum pellentesque. Sed ut arcu eu risus ornare placerat non sodales turpis. Mauris sodales nunc elit, ut convallis neque mattis non.</p>\r\n\r\n<p style=\"text-align:justify\">Donec faucibus gravida arcu, non malesuada nisl imperdiet luctus. Curabitur dictum pellentesque neque, et fermentum risus eleifend vitae. Ut vel egestas diam. Praesent nec diam fermentum, mollis libero sit amet, malesuada purus. Sed quis lectus neque. Fusce a nibh felis. Quisque non justo eu nunc tristique placerat porta sit amet velit. Etiam tempus consequat blandit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>\r\n\r\n<p style=\"text-align:justify\">Phasellus tincidunt velit neque, id imperdiet tortor suscipit non. Praesent sed dui at tellus vulputate tristique. Etiam condimentum mi vel nunc aliquam feugiat sed non nisl. Nunc at dui magna. Ut leo arcu, molestie vitae tristique a, facilisis eu tortor. Mauris suscipit mauris nulla, ut posuere tellus tempor at. Suspendisse nec est sapien. Aliquam tristique aliquam metus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque augue felis, faucibus id tellus eu, egestas posuere orci. Praesent erat metus, commodo at eleifend vel, adipiscing eget massa. Aenean et ornare magna, vitae mattis nulla. Vestibulum malesuada mi felis, sed molestie lacus ultrices non. Mauris convallis odio in nunc elementum blandit. Donec sit amet auctor ligula.</p>\r\n\r\n<p style=\"text-align:justify\">Nulla mollis faucibus pretium. Curabitur eros turpis, lacinia in arcu eu, vehicula auctor enim. Integer ac egestas sapien. Sed blandit turpis eu turpis ultrices, et blandit sapien tristique. Maecenas consectetur semper feugiat. Nunc in sagittis nibh. Sed sodales, sem aliquam dapibus tincidunt, nisl lacus feugiat tortor, a venenatis lectus tortor quis neque. Vestibulum tristique magna nulla, nec posuere nunc facilisis vitae. Cras ut eros lacus. Phasellus turpis sapien, molestie at molestie ac, eleifend quis enim. Nam blandit consectetur ipsum et interdum. Nullam tortor risus, molestie ut adipiscing ut, pellentesque et ante. Nam venenatis, quam ut semper aliquet, sapien purus rutrum arcu, ut pretium leo odio in libero. Nunc dignissim erat lectus.</p>\r\n\r\n<p style=\"text-align:justify\">Maecenas scelerisque viverra sodales. Donec commodo blandit vehicula. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur laoreet, massa non vestibulum sollicitudin, nunc metus placerat nibh, eget placerat ipsum lectus in quam. Etiam ac risus vitae dolor accumsan elementum. Aliquam vitae tincidunt ligula. Curabitur placerat ligula et commodo fringilla.</p>\r\n\r\n<p style=\"text-align:justify\">Proin consectetur felis enim, ac placerat lorem iaculis sed. Suspendisse eu urna rhoncus, vulputate ante eu, luctus tortor. Curabitur nisi lectus, tempus et dolor molestie, scelerisque semper dolor. Cras ac lobortis orci, nec porttitor nisi. Vivamus sodales nisl in mauris hendrerit, sit amet fringilla felis scelerisque. Etiam vitae placerat ipsum. Sed tincidunt tellus non metus condimentum bibendum eu ut ipsum.</p>\r\n\r\n<p style=\"text-align:justify\">Aliquam aliquet porta felis vitae vestibulum. Mauris eget nunc massa. Phasellus ut vestibulum mi. Maecenas vitae ante ligula. Mauris vitae molestie nunc. Nam eget nibh egestas, blandit ante id, pellentesque lectus. Vestibulum non sagittis ipsum. Etiam et consectetur tellus. Proin sodales, urna sit amet malesuada facilisis, est dui ultrices mauris, in accumsan tortor magna vel justo. Nunc suscipit ac lorem eu vehicula. Quisque purus tellus, imperdiet in arcu ac, aliquet ullamcorper odio. Quisque ac orci aliquam, tempus sapien a, mattis lacus. Suspendisse ut fringilla augue. Integer at tellus non lacus elementum dignissim.</p>\r\n\r\n<p style=\"text-align:justify\">Donec rhoncus nisi eget placerat tempus. Nunc iaculis odio ut massa rutrum, in tincidunt eros placerat. Vivamus tincidunt nisi est, vitae tincidunt lectus dignissim ac. In lorem neque, vestibulum eget pharetra ac, rhoncus et nibh. Nunc semper vel felis vulputate volutpat. Aliquam cursus blandit magna. Quisque ac velit nulla. Curabitur sollicitudin nunc urna, et aliquet purus egestas vitae.</p>\r\n\r\n<p style=\"text-align:justify\">Duis id est metus. Nam sed vulputate erat, vitae lobortis ipsum. Praesent eu placerat urna, in tincidunt libero. Cras semper egestas neque, id fringilla lectus consequat ac. Praesent nec augue blandit, laoreet eros eu, egestas orci. Nullam ipsum libero, pretium eu tempor vel, euismod eget nisi. Curabitur a luctus nibh, id venenatis tellus. Duis gravida ipsum a turpis euismod dictum. In id magna at orci vehicula volutpat quis sed orci. Phasellus ut augue hendrerit, sagittis enim vel, vestibulum odio. Sed fringilla bibendum porta. Pellentesque arcu nibh, interdum quis est quis, adipiscing ultrices lorem. Nam non massa cursus, facilisis ante sed, volutpat ipsum. Vivamus euismod gravida suscipit. Phasellus ultricies feugiat arcu faucibus accumsan.</p>\r\n',NULL,0,0),(22,'2014-05-23 11:27:31','2014-05-23 11:29:37','static','about-us-1','About us','<p style=\"text-align:justify\">Fusce ac massa sit amet nisi eleifend ornare quis id est. Vivamus in mi ac justo sodales volutpat. Donec vulputate mi consectetur magna feugiat congue. Etiam nec tincidunt libero, tempus dignissim velit. Nulla lacinia lorem nisi, mollis blandit odio pharetra quis. Ut ut ante vel eros suscipit dignissim. Vivamus posuere dignissim purus, non volutpat metus eleifend vel.</p>\r\n\r\n<p style=\"text-align:justify\">Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus rutrum tempor augue, id aliquet arcu aliquet non. Suspendisse imperdiet mi vitae mauris auctor, ac posuere risus porta. Nunc egestas quis turpis sollicitudin placerat. Nulla facilisi. Phasellus egestas ipsum ligula, a venenatis neque facilisis quis. Nunc enim nibh, pretium ac dolor ut, dictum varius felis. Donec in nunc id turpis egestas volutpat. Ut venenatis lobortis lacus, eget ultricies eros dignissim eu. Ut sodales, lacus ut consectetur accumsan, mi orci faucibus quam, vitae placerat libero libero sit amet sem. Integer eleifend est non magna faucibus luctus. Praesent ut eros sed felis vulputate aliquam vestibulum in lorem. Ut nec tempor turpis.</p>\r\n\r\n<p style=\"text-align:justify\">Integer lacinia augue vehicula turpis fermentum tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque vehicula laoreet massa, ac malesuada risus aliquam sit amet. Quisque vulputate libero ullamcorper faucibus condimentum. Donec nec malesuada nulla. Fusce ac bibendum augue. Morbi nisi mi, facilisis eget libero sit amet, varius euismod sapien. Sed vehicula et lectus quis tristique. Nulla in commodo neque, in ultricies nisi. Nulla sed nibh sit amet magna convallis consequat sed ac orci. Proin imperdiet erat nec mi vulputate, quis porttitor erat iaculis. Pellentesque dapibus diam at ultrices rutrum. Nulla consectetur arcu ac lectus tincidunt, eget scelerisque neque imperdiet. Phasellus semper aliquam mi vitae convallis. Pellentesque eget diam velit. Integer lobortis, libero quis egestas adipiscing, quam lectus faucibus sem, id consequat elit dui id sem.</p>\r\n\r\n<ul class=\"gallery ui-sortable\" data-id=\"1\">\r\n	<li class=\"ui-state-disabled\"><a class=\"addImage\" href=\"#\">+</a><span class=\"removeGallery\">x</span></li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n',NULL,0,0),(29,'2014-05-26 07:20:36','2014-06-05 03:20:47','gallery','background-images-1','Background images','<ul class=\"gallery ui-sortable\" data-id=\"75\">\r\n	<li class=\"ui-state-disabled\"><a class=\"addImage\" href=\"#\">+</a><span class=\"removeGallery\">x</span></li>\r\n	<li id=\"images_399\"><img data-id=\"399\" src=\"/content/images/image/p/a/0/pa0lxxg0/tiny.jpg\" style=\"height:100px; width:100px\" />\r\n	<div class=\"gallery-image-actions\"><a class=\"edit\" href=\"/uploader/files/editImage/399/\">+</a> <a class=\"remove\" href=\"/uploader/files/removeFromList/399/\">+</a></div>\r\n	</li>\r\n	<li id=\"images_398\"><img data-id=\"398\" src=\"/content/images/image/t/3/i/t3if6gjb/tiny.jpg\" style=\"height:100px; width:100px\" />\r\n	<div class=\"gallery-image-actions\"><a class=\"edit\" href=\"/uploader/files/editImage/398/\">+</a> <a class=\"remove\" href=\"/uploader/files/removeFromList/398/\">+</a></div>\r\n	</li>\r\n	<li id=\"images_397\"><img data-id=\"397\" src=\"/content/images/image/2/6/0/260qn0ng/tiny.jpg\" style=\"height:100px; width:100px\" />\r\n	<div class=\"gallery-image-actions\"><a class=\"edit\" href=\"/uploader/files/editImage/397/\">+</a> <a class=\"remove\" href=\"/uploader/files/removeFromList/397/\">+</a></div>\r\n	</li>\r\n	<li id=\"images_396\"><img data-id=\"396\" src=\"/content/images/image/t/2/g/t2gxjusb/tiny.jpg\" style=\"height:100px; width:100px\" />\r\n	<div class=\"gallery-image-actions\"><a class=\"edit\" href=\"/uploader/files/editImage/396/\">+</a> <a class=\"remove\" href=\"/uploader/files/removeFromList/396/\">+</a></div>\r\n	</li>\r\n	<li id=\"images_392\" style=\"position: relative; left: 0px; top: 0px;\"><img data-id=\"392\" src=\"/content/images/image/g/x/y/gxycq9aj/tiny.jpg\" style=\"height:100px; width:100px\" />\r\n	<div class=\"gallery-image-actions\"><a class=\"edit\" href=\"/uploader/files/editImage/392/\">+</a> <a class=\"remove\" href=\"/uploader/files/removeFromList/392/\">+</a></div>\r\n	</li>\r\n	<li id=\"images_395\"><img data-id=\"395\" src=\"/content/images/image/7/a/f/7afqq2b5/tiny.jpg\" style=\"height:100px; width:100px\" />\r\n	<div class=\"gallery-image-actions\"><a class=\"edit\" href=\"/uploader/files/editImage/395/\">+</a> <a class=\"remove\" href=\"/uploader/files/removeFromList/395/\">+</a></div>\r\n	</li>\r\n	<li id=\"images_393\"><img data-id=\"393\" src=\"/content/images/image/k/q/5/kq5gw87h/tiny.jpg\" style=\"height:100px; width:100px\" />\r\n	<div class=\"gallery-image-actions\"><a class=\"edit\" href=\"/uploader/files/editImage/393/\">+</a> <a class=\"remove\" href=\"/uploader/files/removeFromList/393/\">+</a></div>\r\n	</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n',NULL,1,0);

INSERT INTO `plans`(`id`,`name`,`price`) VALUES ( NULL,'15 days ($10)','10');
INSERT INTO `plans`(`id`,`name`,`price`) VALUES ( NULL,'30 days ($20)','20');
INSERT INTO `plans`(`id`,`name`,`price`) VALUES ( NULL,'60 days ($40)','40');
UPDATE `plans` SET `countDays`='15' WHERE `id`='1';
UPDATE `plans` SET `countDays`='30' WHERE `id`='2';
UPDATE `plans` SET `countDays`='60' WHERE `id`='3';

insert  into `settings`(`name`,`key`,`value`,`type`,`rules`,`options`,`root`,`position`) values ('When create company, deny custom mail servers','blockMailServers','1','checkbox','','',0,NULL),('Mail servers domain (google.com, yahoo.com)','mailServers','google.com, yahoo.com, hotmail.com, gmail.com','text','','',0,NULL);

INSERT INTO `skills`(`id`,`name`,`countUsed`) VALUES
 ( NULL,'E-commerce','1000'),
 ( NULL,'SEO','1000'),
 ( NULL,'Email Marketing','1000'),
 ( NULL,'Business Development','1000'),
 ( NULL,'Online Marketing','1000'),
 ( NULL,'Advertising','1000'),
 ( NULL,'Digital Marketing','1000'),
 ( NULL,'New Business Development','1000'),
 ( NULL,'Management','1000'),
 ( NULL,'Negotiation','1000'),
 ( NULL,'QuickBooks','1000'),
 ( NULL,'Strategic Planning','1000'),
 ( NULL,'Budgets','1000'),
 ( NULL,'Online Advertising','1000'),
 ( NULL,'Sales Management...','1000'),
 ( NULL,'PPC','1000'),
 ( NULL,'Public Relations','1000'),
 ( NULL,'Digital Media','1000'),
 ( NULL,'MySQL','1000'),
 ( NULL,'PHP','1000'),
 ( NULL,'CSS','1000'),
 ( NULL,'Real Estate ','1000'),
 ( NULL,'Leadership ','1000'),
 ( NULL,'Due Diligence ','1000'),
 ( NULL,'Recruiting ','1000'),
 ( NULL,'Marketing ','1000'),
 ( NULL,'Integrated Marketing ','1000'),
 ( NULL,'Partnerships ','1000'),
 ( NULL,'New Business Development ','1000'),
 ( NULL,'Contract Negotiation ','1000'),
 ( NULL,'Strategic Partnerships ','1000'),
 ( NULL,'Executive Management ','1000'),
 ( NULL,'Awesomeness','1000'),
 ( NULL,'Green','1000'),
 ( NULL,'Public Relations','1000'),
 ( NULL,'Entrepreneurship','1000'),
 ( NULL,'Digital Media','1000'),
 ( NULL,'Brand Development','1000'),
 ( NULL,'E-commerce','1000'),
 ( NULL,'Renewable Energy','1000'),
 ( NULL,'Corporate Social...','1000'),
 ( NULL,'Online Marketing','1000'),
 ( NULL,'Online Advertising','1000'),
 ( NULL,'Energy','1000'),
 ( NULL,'Social Networking','1000'),
 ( NULL,'Environmental Awareness','1000'),
 ( NULL,'Business Development','1000'),
 ( NULL,'Marketing Strategy','1000'),
 ( NULL,'New Business Development','1000'),
 ( NULL,'Digital Marketing','1000'),
 ( NULL,'Marketing Communications','1000'),
 ( NULL,'Lead Generation','1000'),
 ( NULL,'Strategic Planning','1000'),
 ( NULL,'Email Marketing','1000'),
 ( NULL,'Sales','1000'),
 ( NULL,'Integrated Marketing','1000'),
 ( NULL,'Business Strategy','1000'),
 ( NULL,'SEO','1000'),
 ( NULL,'Strategic Partnerships','1000'),
 ( NULL,'Start-ups','1000'),
 ( NULL,'Web Marketing','1000'),
 ( NULL,'Digital Strategy','1000'),
 ( NULL,'Sustainability Strategy','1000'),
 ( NULL,'Research','1000'),
 ( NULL,'Writing','1000'),
 ( NULL,'LEED AP','1000'),
 ( NULL,'Business Planning','1000'),
 ( NULL,'Product Development','1000'),
 ( NULL,'Vendor Management ','1000'),
 ( NULL,'Operations Management ','1000'),
 ( NULL,'B2B ','1000'),
 ( NULL,'International Business ','1000'),
 ( NULL,'Email Marketing ','1000'),
 ( NULL,'Sales Process ','1000'),
 ( NULL,'Online Marketing ','1000'),
 ( NULL,'Supply Chain Management ','1000'),
 ( NULL,'Export ','1000'),
 ( NULL,'Management ','1000'),
 ( NULL,'Marketing Strategy ','1000'),
 ( NULL,'CRM ','1000'),
 ( NULL,'PPC ','1000'),
 ( NULL,'Microsoft Office ','1000'),
 ( NULL,'Microsoft Excel ','1000'),
 ( NULL,'Supply Chain ','1000'),
 ( NULL,'Entrepreneurship ','1000'),
 ( NULL,'Call Centers ','1000'),
 ( NULL,'Call Center ','1000'),
 ( NULL,'Project Management ','1000'),
 ( NULL,'Procurement ','1000'),
 ( NULL,'Technical Recruiting ','1000'),
 ( NULL,'Logistics Management ','1000'),
 ( NULL,'Leadership ','1000'),
 ( NULL,'Email Marketing ','1000'),
 ( NULL,'New Business Development ','1000'),
 ( NULL,'Web Development ','1000'),
 ( NULL,'Google Adwords ','1000'),
 ( NULL,'Web Analytics ','1000'),
 ( NULL,'Small Business ','1000'),
 ( NULL,'SEM ','1000'),
 ( NULL,'Integrated Marketing ','1000'),
 ( NULL,'Product Development ','1000'),
 ( NULL,'Mobile Applications ','1000'),
 ( NULL,'Marketing Strategy ','1000'),
 ( NULL,'Strategy ','1000'),
 ( NULL,'Analytics ','1000'),
 ( NULL,'Strategic Partnerships ','1000'),
 ( NULL,'Web Marketing ','1000'),
 ( NULL,'Google Analytics ','1000'),
 ( NULL,'Venture Capital ','1000'),
 ( NULL,'Computer Science ','1000'),
 ( NULL,'Entrepreneur ','1000'),
 ( NULL,'Angel Investing ','1000'),
 ( NULL,'Mobile Devices ','1000'),
 ( NULL,'SaaS ','1000'),
 ( NULL,'Yandex PPC ','1000'),
 ( NULL,'XML ','1000'),
 ( NULL,'Ruby ','1000'),
 ( NULL,'MySQL ','1000'),
 ( NULL,'Git ','1000'),
 ( NULL,'XHTML ','1000'),
 ( NULL,'Web Applications ','1000'),
 ( NULL,'CSS ','1000'),
 ( NULL,'Apache ','1000'),
 ( NULL,'REST ','1000'),
 ( NULL,'Test Driven Development ','1000'),
 ( NULL,'SEO ','1000'),
 ( NULL,'Subversion ','1000'),
 ( NULL,'Software Engineering ','1000'),
 ( NULL,'Project Management ','1000'),
 ( NULL,'Python ','1000'),
 ( NULL,'JSON ','1000'),
 ( NULL,'Agile Methodologies ','1000'),
 ( NULL,'Entrepreneurship ','1000'),
 ( NULL,'Small Business ','1000'),
 ( NULL,'.NET ','1000'),
 ( NULL,'SOA ','1000'),
 ( NULL,'IT Infrastructure... ','1000'),
 ( NULL,'Software Project... ','1000'),
 ( NULL,'Requirements Gathering ','1000'),
 ( NULL,'Scrum ','1000'),
 ( NULL,'Balanced Scorecard ','1000'),
 ( NULL,'Languages ','1000'),
 ( NULL,'Website Development ','1000'),
 ( NULL,'Database Administration ','1000'),
 ( NULL,'Analytics ','1000'),
 ( NULL,'Cross-functional Team...','1000'),
 ( NULL,'Web Applications','1000'),
 ( NULL,'Software Engineering','1000'),
 ( NULL,'MySQL','1000'),
 ( NULL,'Agile Project Management','1000'),
 ( NULL,'Test Driven Development','1000'),
 ( NULL,'Enterprise Architecture','1000'),
 ( NULL,'Bash','1000'),
 ( NULL,'Apache','1000'),
 ( NULL,'SOA','1000'),
 ( NULL,'AJAX','1000'),
 ( NULL,'Financial Modeling','1000'),
 ( NULL,'Due Diligence','1000'),
 ( NULL,'Sarbanes-Oxley Act','1000'),
 ( NULL,'Restructuring','1000'),
 ( NULL,'Financial Analysis','1000'),
 ( NULL,'External Audit','1000'),
 ( NULL,'Revenue Recognition','1000'),
 ( NULL,'Big 4','1000'),
 ( NULL,'SEC Filings','1000'),
 ( NULL,'Auditing','1000'),
 ( NULL,'Financial Accounting','1000'),
 ( NULL,'Valuation','1000'),
 ( NULL,'Market Analysis ','1000'),
 ( NULL,'Competitive Intelligence ','1000'),
 ( NULL,'Predictive Modeling ','1000'),
 ( NULL,'Consumer Behaviour ','1000'),
 ( NULL,'Business Strategy ','1000'),
 ( NULL,'Strategy ','1000'),
 ( NULL,'Statistical Modeling ','1000'),
 ( NULL,'Data Analysis ','1000'),
 ( NULL,'SAS ','1000'),
 ( NULL,'Database Marketing ','1000'),
 ( NULL,'Business Intelligence ','1000'),
 ( NULL,'Data Mining ','1000'),
 ( NULL,'Marketing Strategy ','1000'),
 ( NULL,'Quantitative Research ','1000'),
 ( NULL,'Logistic Regression ','1000'),
 ( NULL,'Pricing Strategy ','1000'),
 ( NULL,'Management Consulting ','1000'),
 ( NULL,'Web Analytics ','1000'),
 ( NULL,'FMCG ','1000'),
 ( NULL,'Strategic Consulting ','1000'),
 ( NULL,'Customer Analytics ','1000'),
 ( NULL,'Online Marketing ','1000'),
 ( NULL,'Go-to-market Strategy ','1000'),
 ( NULL,'SEM ','1000'),
 ( NULL,'Brand Equity ','1000'),
 ( NULL,'Optimization ','1000'),
 ( NULL,'Qualitative Research ','1000'),
 ( NULL,'E-commerce ','1000'),
 ( NULL,'Consumer Products ','1000'),
 ( NULL,'Marketing Operations ','1000'),
 ( NULL,'Product Management ','1000'),
 ( NULL,'SAS programming ','1000'),
 ( NULL,'Consumer Insights ','1000'),
 ( NULL,'Marketing ROI ','1000'),
 ( NULL,'Strategic Planning ','1000'),
 ( NULL,'SEO ','1000'),
 ( NULL,'SAS/SQL ','1000'),
 ( NULL,'Regression ','1000'),
 ( NULL,'Product Strategy ','1000'),
 ( NULL,'Business Analysis','1000');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
